import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import 'react-phone-number-input/style.css'
import PhoneInput from 'react-phone-number-input'

export default function Home() {
  const [employeeName, setEmployeeName] = useState("");
  const [phoneNumber, setValue] = useState("");
  const [title, setTitle] = useState("");
  const [messageBody, setMessageBody] = useState("");
  const [sent, setSent] = useState(false);

  const sendData = async (event) => {
    event.preventDefault();

    const data1 = {
      name: employeeName, 
      messageTitle: title,
      message: messageBody,
    }

    const mainObject1 = JSON.stringify(data1);

    const endPoint1 = '/api/textAI';
    const params1 = {
      method: 'POST',
      body: mainObject1,
    }

    const response = await fetch(endPoint1, params1);
  
    const myData = await response.json();
    const {textData} = myData;
   
    console.log(`this is data is from openAIApi: ${textData} `)

    const data2 = {
      number: phoneNumber,
      text: textData
    }

    const mainObject2 = JSON.stringify(data2)

    const endPoint2 = 'api/data';

    const params2 = {
      method: 'POST',
      body: mainObject2,
    }

    const response2 = await fetch(endPoint2, params2);
    const myData2 = await response2.json();
    console.log(`this is the twilio response to the frontend: ${JSON.stringify(myData2)} `);
    const {err} = myData2;
    
    if (!err){
      setSent(true);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.formContent}>
        <div className={styles.header}>
          <h1>Meeting Inviter</h1>
        </div>

        <div >
          <form className={styles.inputForm} onSubmit={sendData}method='POST'>
            <input className={styles.input} type='text' name='employeeName' placeholder='Name of employee'onChange={(e) => setEmployeeName(e.target.value)}/>
            <PhoneInput
              className={styles.phoneNumber}
              placeholder='Enter Employee number'
              value={phoneNumber}
              onChange={setValue}
            />
            <input className={styles.input} type='text' name='messageBody' placeholder='Enter meeting title' onChange={(e) => setTitle(e.target.value)}/>
            <textarea className={styles.textArea} placeholder='Enter meeting descreiption' rows='10' cols='30' onChange={(e) => setMessageBody(e.target.value)} />
            <button className={styles.button} type='submit'>Send</button>
          </form>
          <div>{sent && (
            <div className={styles.alert}>Message sent</div>
          )}
          </div>
        </div>
      </div>
    </div>
  )
}
